# Generated by Django 5.0 on 2024-01-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Record',
        ),
    ]
